[project]
name = "opslib-cloudflare"
version = "0.0.1"
dependencies = [
    "pyopslib",
]

[project.optional-dependencies]
dev = [
    "pyright",
]

[tool.setuptools]
packages = [
    "opslib_cloudflare",
]
